export const ALL_APPLICATION_REQUEST = "ALL_APPLICATION_REQUEST"
export const ALL_APPLICATION_SUCCESS = "ALL_APPLICATION_SUCCESS"
export const ALL_APPLICATION_FAIL = "ALL_APPLICATION_FAIL"


export const APPLICATION_DETAILS_REQUEST = "APPLICATION_DETAILS_REQUEST"
export const APPLICATION_DETAILS_SUCCESS = "APPLICATION_DETAILS_SUCCESS"
export const APPLICATION_DETAILS_FAIL = "APPLICATION_DETAILS_FAIL"

export const CLEAR_ERROR = "CLEAR_ERROR"