export const ALL_DOMAIN_REQUEST = "ALL_DOMAIN_REQUEST"
export const ALL_DOMAIN_SUCCESS = "ALL_DOMAIN_SUCCESS"
export const ALL_DOMAIN_FAIL = "ALL_DOMAIN_FAIL"


export const DOMAIN_DETAILS_REQUEST = "DOMAIN_DETAILS_REQUEST"
export const DOMAIN_DETAILS_SUCCESS = "DOMAIN_DETAILS_SUCCESS"
export const DOMAIN_DETAILS_FAIL = "DOMAIN_DETAILS_FAIL"

export const CLEAR_ERROR = "CLEAR_ERROR"